# (PART) Habitat Models {-} 

# Background on habitat models in USACE

THIS IS AN INTRO TO HABITAT MODELS IN GENERAL; CONSIDER WHETHER TO PARE DOWN OR REMOVE

Across all business lines, the U.S. Army Corps of Engineers (USACE) engages in a large variety of decisions that affect a multitude ecological outcomes (e.g., ecosystem restoration of oyster reefs, environmental flows for imperiled fishes, and bird breeding grounds impacted by dredge material management). While numerous aquatic, riparian, and terrestrial analytical tools exist, ecological models typically have not been easily accessible or in the most usable form for field practitioners and often require significant data and modeling expertise to effectively employ. However, ecological models must be used to quantify environmental impacts and benefits throughout the project life-cycle of planning, engineering, construction, operations, and maintenance. 

A common approach to ecological modeling of environmental impacts and benefits is based on quantity and quality of habitat. These "index" models (Swannack et al. 2012) were originally developed for species-specific applications (e.g., slider turtles), but the general approach has also been adapted to guilds (e.g., salmonids), communities (e.g., floodplain vegetation), and ecosystem processes (e.g., the Hydrogeomorphic Method). No standard platform for exists for computing outcomes from index models, and users often develop ad hoc spreadsheet models, which are highly prone to numerical errors (McKay 2009). The common quantity-quality structure of index models provides an opportunity to develop a consistent, error-checked index modeling calculator adaptable to a variety of applications across the Corps.

Furthermore, ecological modeling often seeks to inform trade-offs between a monetary assessment of social benefits or costs (e.g., restoration investment cost or economic damages avoided) and a non-monetary assessment of environmental benefits and costs (e.g., habitat gains of restoration or impact to an imperiled taxa's habitat). Cost-effectiveness and incremental cost analyses (CEICA) provide a useful set of techniques for comparing non-monetary and monetary costs and benefits of management actions (Robinson et al. 1995). CEICA is commonly applied in planning and designing ecosystem restoration projects and is often coupled with index models to inform management decisions.  


#### *2.1. Index-Based Ecological Models*  


Ecological models have become common tools for informing decisions related to the management of complex ecological processes. Models span the breadth of their potential ecological management applications such as seafood harvest limits, transport of nutrients into freshwaters, bioaccumulation of contaminants, management of imperiled taxa, and wetland impact assessment. In addition to diverse outcomes, ecological models often take on a variety of theoretical constructs ranging from theoretical, analytical models to statistical correlations of variables to agent-based simulations of animal movement (See Swannack et al. 2012 for a review of ecological model types). The diversity of ecological endpoints and model constructs has led to a wide array of tools applicable to ecosystem management and restoration.  

Index models are a family of techniques commonly applied in planning ecosystem restoration projects. Briefly, index models quantitatively translate multiple features or processes into a relative assessment of habitat suitability for a given organism or a relative assessment of ecosystem condition (Tirpak et al. 2009, Swannack et al. 2012). More specifically, index models combine assessments of habitat or ecosystem quality and quantity into an overarching metric for assessing the relative condition of a site (e.g., a "habitat unit" or "functional capacity unit"). Quantity is commonly expressed as a metric of area such as acres or hectares; however, other metrics may be appropriate to specific applications such as river length or lake volume. Quality is then assessed by identifying key variables correlated with habitat or ecosystem condition. Each variable is then translated into a suitability index curve, which transforms dimensional quantities such as flow velocity into dimensionless values of quality (0 to 1 where 0 is unsuitable/low condition and 1 is suitable/ideal condition). Multiple suitability curves are then combined through various equational forms into an overarching assessment of habitat quality (e.g., a "habitat suitability index" or "functional capacity index"). 

Index models may be derived from a variety of methods and resources. Like all models, many index model developers have emphasized that these algorithms simplify complex ecosystems, and thus, these tools should be considered adaptable hypotheses rather than mechanistic, cause-effect relationships. The value of index models lies in their utility for quantitatively comparing the relative merits of alternative management actions and testing hypotheses. The following represent the most common sources of index models applied to USACE ecosystem restoration projects:  

* *U.S. Fish and Wildlife Service (USFWS) Habitat Suitability Index (HSI) Models:* The HSI approach quantitatively relates potential for species presence to habitat characteristics. Species have complex relationships with their environment, and HSI models provide a simple method for characterizing potential for habitat to support target species across a landscape. The USFWS led the development of 500+ HSI models in the 1970-1980s to support environmental management decisions nationwide (https://www.nwrc.usgs.gov/wdb/pub/hsi/hsiindex.htm). The quantitative relationships between species and habitat were generally based on a combination of literature, field studies, and expert opinion, and the reports are colloquially referred to as the "blue books" because of the blue covers binding the original publications.    
* *Hydrogeomorphic Method (HGM) of Wetland Assessment:* Similarly, the HGM approach is a common technique for rapidly assessing wetland function. The HGM methodology for model development is thoroughly documented (Brinson 1993, Smith et al. 1995), and models are available for 30+ wetland types nationwide (https://wetlands.el.erdc.dren.mil/guidebooks.cfm).  
* *Literature-Based Index Models:* Index models also appear within the peer-reviewed and grey literature in a variety of formats. Some of the original HSI models have been subsequently adapted to local conditions or updated as new data became available (e.g., the bluegill model by Stuber et al. 1982 was adapted by Palesh and Anderson 1990). Models also appear in the peer-reviewed literature as new data become available, such as a recent revision to oyster suitability models which expands the breadth of applicability (Swannack et al. 2014).
* *Project- or Objective-Centric Index Models:* Specific restoration projects may build models unique to a set of project objectives (McKay et al. 2019), which can evolve as a project proceeds from preliminary screening to detailed alternatives analysis (e.g., McKay et al. 2018ab). More recently, Carrillo et al. (2020) proposed a Toolkit for interActive Modeling (TAM), which facilitates development of index models in real-time for mediated modeling workshop settings (Herman et al. 2019).


#### *2.2. Cost-Effectiveness and Incremental Cost Analysis (CEICA)*  


The USACE ecosystem restoration mission was first authorized in the Water Resources Development Act of 1986 with the stated purpose “…to restore significant structure, function and dynamic processes that have been degraded” (USACE 1999, ER 1165-2-501). Given this goal, USACE programs emphasize ecological outcomes (as opposed to social or economic outcomes). Generally, ecological resources may be quantified in a variety of ways ranging from habitat suitability for a focal taxa (e.g., an endangered species) to changes in physical processes (e.g., sediment delivery from geomorphic change) to changes in biological processes (e.g., carbon uptake and storage). In other USACE business lines (e.g., navigation), costs and benefits of actions are compared in monetary terms, and the benefit-cost ratio serves as a crucial decision metric. However, outputs of restoration are typically not monetized, and a different set of methods are required to inform restoration decision-making and address the issue of “Is ecosystem restoration worth the Federal investment?” In particular, cost-effectiveness and incremental cost analyses provide techniques for comparing non-monetary ecological benefits relative to monetary costs of restoration actions (Robinson et al. 1995).

Cost-effectiveness and incremental cost analyses (CEICA) are analytical tools for assessing the relative benefits and costs of ecosystem restoration actions and informing decisions. Benefits and costs are assessed prior to these analyses using ecological models (e.g., index models) and cost engineering methods, respectively. CEICA may then be conducted at the site scale to compare alternatives at a single location (e.g., no action vs. dam removal vs. fish ladder) or at the system scale to compare relative merits of multiple sites (e.g., no sites vs. Site-A only vs. Site-B only vs. Site-A and Site-B). Within the USACE, the Institute of Water Resources has provided a toolkit for conducting CEICA, the IWR Planning Suite (http://www.iwr.usace.army.mil/Missions/Economics/IWR-Planning-Suite/).

Cost-effectiveness analysis provides a mechanism for examining the efficiency of alternative actions. For any given level of investment, the agency wants to identify the plan with the most return-on-investment (i.e., the most environmental benefits), and for any given level of environmental benefits, the agency wants a plan with the least cost. An “efficiency frontier” identifies all plans that efficiently provide benefits on a per cost basis (i.e., cost-effective plans). These "non-dominated" alternatives compose the Pareto-optimal frontier.

Incremental cost analysis is conducted on the set of cost-effective plans. This technique sequentially compares each plan to all higher cost plans to reveal changes in unit cost as output levels increase and eliminates plans that do not efficiently provide benefits on a per unit cost basis. Specifically, this analysis examines the slope of the cost-effectiveness frontier to isolate how the incremental unit cost ($/unit) increases as the magnitude of environmental benefit increases. Incremental cost analysis is ultimately intended to inform decision-makers about the consequences of increasing unit cost when increasing benefits (i.e., each unit becomes more expensive). Plans emerging from incremental cost analysis efficiently accomplish the objective relative to unit costs and are typically referred to as “best buys”. Importantly, all “best buys” are cost-effective, but all cost-effective plans are not best buys.



### Include TAM model here?